creation_rules:
  - path_regex: ^\.env$
    age: "age1qw643dna4spaup6sr5ap0jf039ncjd54e8ekvrfy6p6x96ys2y4qn5vcsy"
  - path_regex: ^secrets/
    age: "age1qw643dna4spaup6sr5ap0jf039ncjd54e8ekvrfy6p6x96ys2y4qn5vcsy"