creation_rules:
  - path_regex: ^\.env$
    age: "age1p4uvxng3vwjr3s465u37s346snmvr0ksus8e0eclutvmrjyh89zspfts9d"
  - path_regex: ^secrets/
    age: "age1p4uvxng3vwjr3s465u37s346snmvr0ksus8e0eclutvmrjyh89zspfts9d"