---
- Infrastructure:
    - OCI Console:
        - abbr: OCI
          href: https://cloud.oracle.com
    - Tailscale:
        - abbr: TS
          href: https://login.tailscale.com/admin/machines
    - Cloudflare:
        - abbr: CF
          href: https://dash.cloudflare.com

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/deuxksy
    - dotfiles:
        - abbr: DF
          href: https://github.com/deuxksy/dotfiles
    - "24/7/365":
        - abbr: "247"
          href: https://github.com/deuxksy/twenty-four-seven-three-sixty-five
