- Info:
    - Calendar:
        widget:
          type: calendar
          firstDayInWeek: sunday
          view: monthly
          timezone: Asia/Seoul
          integrations:
            - type: ical
              url: https://calendar.google.com/calendar/ical/deuxksy%40gmail.com/public/basic.ics
              name: Google Calendar
              color: amber
    - Stocks:
        widget:
          type: stocks
          provider: finnhub
          watchlist:
            - EWY
            - SPY
            - QQQ
            - ASHR
            - KSTR
            - EWJ
            - INDY
            - VNM
            - FEZ

    - Agenda:
        widget:
          type: calendar
          view: agenda
          maxEvents: 10
          showTime: true
          previousDays: 3
          integrations:
            - type: ical
              url: https://calendar.google.com/calendar/ical/deuxksy%40gmail.com/public/basic.ics
              name: Google Calendar
              color: amber

- Monitoring:
    - Beszel:
        label: "Service Monitor"
        icon: beszel.png
        href: https://brla.bun-bull.ts.net:8090
        server: my-docker
        container: beszel-hub
        widget:
          type: beszel
          url: http://beszel-hub:8090
          username: {{HOMEPAGE_VAR_BESZEL_USERNAME}}
          password: {{HOMEPAGE_VAR_BESZEL_PASSWORD}}
          version: 2

    - Gatus:
        label: "Uptime Monitor"
        icon: gatus.png
        href: https://brla.bun-bull.ts.net:8088
        server: my-docker
        container: gatus
        widget:
          type: gatus
          version: 2
          url: http://gatus:8088

- Development:
    - Hermes:
        label: "AI Gateway"
        href: https://brla.bun-bull.ts.net:9119
        server: my-docker
        container: hermes

    - code-server:
        label: "VS Code Server"
        icon: code.png
        href: https://brla.bun-bull.ts.net:8080
        server: my-docker
        container: code-server
