# ansible/roles/traefik/tasks/main.yml

- name: Traefik 디렉토리 생성
  file:
    path: "{{ traefik_data_dir }}"
    state: directory
    owner: ubuntu
    group: ubuntu

- name: Traefik 정적 설정 배포
  copy:
    src: traefik.yml
    dest: "{{ traefik_data_dir }}/traefik.yml"
    owner: ubuntu
    group: ubuntu
    mode: "0644"

- name: Traefik 동적 설정 배포
  template:
    src: dynamic.yml.j2
    dest: "{{ traefik_data_dir }}/dynamic.yml"
    owner: ubuntu
    group: ubuntu
    mode: "0644"

- name: Traefik Docker Compose 파일 생성
  template:
    src: docker-compose.yml.j2
    dest: "{{ traefik_data_dir }}/docker-compose.yml"
    owner: ubuntu
    group: ubuntu

- name: Traefik 컨테이너 시작
  shell: docker compose up -d
  args:
    chdir: "{{ traefik_data_dir }}"
