entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  code:
    address: ":8080"
  gatus:
    address: ":8088"
  beszel:
    address: ":8090"
  hermes:
    address: ":9119"

providers:
  docker:
    exposedByDefault: false
    network: proxy
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: INFO
